/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv19.ui;

import com.cv19.dao.DAOFactory;
import com.cv19.dao.DatabaseCallback;
import com.cv19.dao.HandshakeRequest;
import com.cv19.dao.UserDAO;
import com.cv19.dao.models.Review;
import com.cv19.dao.models.User;
import java.awt.CardLayout;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rafdi
 */
public class HomeUI extends javax.swing.JFrame implements DatabaseCallback {

    /**
     * Creates new form HomeUI
     */
    
    CardLayout cl;
    UserDAO userDao;
    
    public HomeUI() {
        initComponents();
        userDao = DAOFactory.getDAOInstance().getUserDAO();
        initRadioButtonGroup();
        initCardLayout();
    }
  
    public void initCardLayout(){
        cl = (CardLayout) pMainContainer.getLayout();
        cl.show(pMainContainer, "pHome");
    }
    
    public void initRadioButtonGroup(){
        rbGroup.add(rbEmail);
        rbGroup.add(rbID);
        rbGroup.add(rbUsername);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGroup = new javax.swing.ButtonGroup();
        pMainContainer = new javax.swing.JPanel();
        pHome = new javax.swing.JPanel();
        bToSearchDB = new javax.swing.JButton();
        pSearchDB = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        eSearchInput = new javax.swing.JTextField();
        bSearch = new javax.swing.JButton();
        rbEmail = new javax.swing.JRadioButton();
        rbID = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbUsername = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pMainContainer.setLayout(new java.awt.CardLayout());

        bToSearchDB.setText("Cerca nel Database");
        bToSearchDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bToSearchDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pHomeLayout = new javax.swing.GroupLayout(pHome);
        pHome.setLayout(pHomeLayout);
        pHomeLayout.setHorizontalGroup(
            pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHomeLayout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(bToSearchDB)
                .addContainerGap(384, Short.MAX_VALUE))
        );
        pHomeLayout.setVerticalGroup(
            pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHomeLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(bToSearchDB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );

        pMainContainer.add(pHome, "card4");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        eSearchInput.setToolTipText("");

        bSearch.setText("Cerca");
        bSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearchActionPerformed(evt);
            }
        });

        rbEmail.setText("Email");
        rbEmail.setActionCommand("Email");
        rbEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEmailActionPerformed(evt);
            }
        });

        rbID.setText("ID");
        rbID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIDActionPerformed(evt);
            }
        });

        jLabel1.setText("Cerca per:");

        jLabel3.setText("Database");

        rbUsername.setText("Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(rbEmail)
                        .addGap(18, 18, 18)
                        .addComponent(rbID)
                        .addGap(18, 18, 18)
                        .addComponent(rbUsername))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(eSearchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eSearchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rbEmail)
                    .addComponent(rbID)
                    .addComponent(rbUsername))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pSearchDBLayout = new javax.swing.GroupLayout(pSearchDB);
        pSearchDB.setLayout(pSearchDBLayout);
        pSearchDBLayout.setHorizontalGroup(
            pSearchDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchDBLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        pSearchDBLayout.setVerticalGroup(
            pSearchDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchDBLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );

        pMainContainer.add(pSearchDB, "card3");

        getContentPane().add(pMainContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static final int CALLBACK_QUERY_USERNAME = 0;
    public static final int CALLBACK_QUERY_EMAIL = 0;
    public static final int CALLBACK_QUERY_ID = 0;
    
    public void initQuery(String searchString){
        switch(rbGroup.getSelection().getActionCommand()){
            case "Username":
                userDao.getUserByUsername(searchString, this, CALLBACK_QUERY_USERNAME);
                break;
            case "Email":
                userDao.getUserByEmail(searchString, this, CALLBACK_QUERY_EMAIL);
                break;
            case "ID":
                userDao.getUserByID(searchString, this, CALLBACK_QUERY_ID);
                break;
        }
    }
    
    private void bToSearchDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bToSearchDBActionPerformed
        pMainContainer.removeAll();
        pMainContainer.add(pSearchDB);
        pMainContainer.revalidate();
    }//GEN-LAST:event_bToSearchDBActionPerformed

    private void bSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchActionPerformed
        bSearch.setEnabled(false);
        initQuery(eSearchInput.getText());
    }//GEN-LAST:event_bSearchActionPerformed

    private void rbEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEmailActionPerformed

    private void rbIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUI().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSearch;
    private javax.swing.JButton bToSearchDB;
    private javax.swing.JTextField eSearchInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pHome;
    private javax.swing.JPanel pMainContainer;
    private javax.swing.JPanel pSearchDB;
    private javax.swing.JRadioButton rbEmail;
    private javax.swing.ButtonGroup rbGroup;
    private javax.swing.JRadioButton rbID;
    private javax.swing.JRadioButton rbUsername;
    // End of variables declaration//GEN-END:variables

    @Override
    public void callback(int callbackCode) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void callback(String message, int callbackCode) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void callback(HandshakeRequest hreq, String id, int callbackCode) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void callback(boolean response, int callbackCode) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void reviewsCallback(List<Review> reviews, int callbackCode) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    @Override
    public void showError(Exception e, int callbackCode) {
        JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            try {
                Thread.sleep(10000);
            } catch (InterruptedException ex) {
                Logger.getLogger(AuthUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            bSearch.setEnabled(true);
    }

    @Override
    public void callback(User user, int callbackCode) {
        new UserResultUI(user).setVisible(true);
        bSearch.setEnabled(true);
    }
}
